export const MainTypes = {
  SET_COUNTRIES: "MainTypes/SET_COUNTRIES",
  SET_COUNTRY_FROM: "MainTypes/SET_COUNTRY_FROM",
  SET_COUNTRY_TO: "MainTypes/SET_COUNTRY_TO",
  SET_CURRENCY_FROM: "MainTypes/SET_CURRENCY_FROM",
  SET_CURRENCY_TO: "MainTypes/SET_CURRENCY_TO",
  SET_VALUE:'MainTypes/SET_VALUE',
  SET_IS_SENDER:'MainTypes/SET_IS_SENDER',
  SET_PAYMENT:'MainTypes/SET_PAYMENT',
  SET_PAYMENT_LIST:'MainTypes/SET_PAYMENT_LIST'

};
